#####
cractus-withfp-opt-id - Run 1
2024-02-22 03:53:51
#####
python3: can't open file '/home/ubuntu/.phoronix-test-suite/installed-tests/system/selenium-1.0.38/./run-benchmark.py': [Errno 2] No such file or directory

#####
cractus-withfp-opt-id - Run 2
2024-02-22 03:53:55
#####
python3: can't open file '/home/ubuntu/.phoronix-test-suite/installed-tests/system/selenium-1.0.38/./run-benchmark.py': [Errno 2] No such file or directory

#####
cractus-withfp-opt-id - Run 3
2024-02-22 03:53:57
#####
python3: can't open file '/home/ubuntu/.phoronix-test-suite/installed-tests/system/selenium-1.0.38/./run-benchmark.py': [Errno 2] No such file or directory

