#####
fp-fp-py-id - Run 1
2024-02-24 09:57:31
#####
Benchmarking on 12 threads
Traceback (most recent call last):
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/pytorch-benchmark.py", line 8, in <module>
    model = resnet50().to("cuda")
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

#####
fp-fp-py-id - Run 2
2024-02-24 09:57:37
#####
Benchmarking on 12 threads
Traceback (most recent call last):
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/pytorch-benchmark.py", line 8, in <module>
    model = resnet50().to("cuda")
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

#####
fp-fp-py-id - Run 3
2024-02-24 09:57:41
#####
Benchmarking on 12 threads
Traceback (most recent call last):
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/pytorch-benchmark.py", line 8, in <module>
    model = resnet50().to("cuda")
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.phoronix-test-suite/installed-tests/pts/pytorch-1.0.1/.local/lib/python3.11/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

